### ISSUE TITLE
[Bug] - UI doesn't update properly after deleting a file.

### ISSUE THREAD

**Issue by mattjanus** [eldertek/duplicatefinder#59] opened 2024-02-27 04:22 UTC
**Describe the bug**
When deleting a duplicate, it get's deleted as it should and it momentarily is hidden in the UI and the notification is displayed that the duplicate was deleted but then it shows the file again.

If you refresh the dupe is gone. If you attempt to delete it again instead of refreshing, you get an error that it was unable to delete a file, but then it does refresh the ui correctly.

**To Reproduce**
1. Delete a dupe
2. Observe the success message
3. Observe the ui isn't refreshed properly

**Expected behavior**
When the dupe has successfully been deleted, it should automatically move to the next dupe in the list.

**Versions**
- Nextcloud 28.0.2
- Duplicate Finder 1.1.8

**Comment by Routhinator** [comment] 2024-02-27 13:52
I believe this is related to UX Issue 1 in #58

**Comment by eldertek** [comment] 2024-03-22 17:23
Closing as it is a duplicate of #58

**Closed by eldertek** 2024-03-22 17:23 UTC
Labels: bug
